name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Restore packages
      run: yarn
    
    - name: Build
      run: yarn build
       
    - name: Prettier
      run: yarn prettier:check
      
    - name: Test
      run: yarn test
      
