name: Build and publish master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
        
    - name: Restore packages
      run: yarn
    
    - name: Build
      run: yarn build
       
    # - name: Prettier
    #   run: yarn prettier:check
      
    # - name: Test
    #   run: yarn test

    - name: Configure NPM
      run: |
        echo "@nth-commit:registry=https://npm.pkg.github.com/" > .npmrc
        echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc

    - name: Publish pre-release packages
      run: yarn run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHA: ${GITHUB_SHA::8}
