name: Build pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_OPTIONS: --max_old_space_size=8192

    steps:
    - uses: actions/checkout@v2

    - name: Restore packages
      run: yarn

    - name: Build
      run: yarn build

    - name: Prettier
      run: yarn prettier:check

    - name: Test
      run: yarn test
