name: Build and publish master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Restore packages
      run: yarn

    - name: Build
      run: yarn build

    - name: Prettier
      run: yarn prettier:check

    - name: Test
      run: yarn test

    - name: Configure NPM
      run: echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' >> .npmrc

    - name: Publish pre-release packages
      run: |
        yarn lerna publish --yes --registry 'https://registry.npmjs.org' --canary --pre-dist-tag latest --force-publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
