name: Test master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_OPTIONS: --max_old_space_size=8192

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Restore packages
      run: yarn

    - name: Test
      run: yarn test:deep

